# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_trabajador_registrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.SmallIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cdRDC', models.BooleanField(default=True)),
                ('dvdRDC', models.BooleanField(default=True)),
                ('penRDC', models.BooleanField(default=True)),
                ('Trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Trabajador')),
            ],
        ),
    ]
