# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiposTrabajos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Trabajo',
                'verbose_name_plural': 'Tipos de Trabajos',
            },
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tipo',
            field=models.ManyToManyField(to='trabajos.tiposTrabajos'),
        ),
    ]
