# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0005_auto_20170612_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Trabajador'),
        ),
    ]
